#
# Szene makefile for DJGPP version (GNU-make)
#

EXE=plushplr.exe matedit2.exe

LIB=plush/libplush.a contrib/grx248/lib/dj2/libgrx20.a Depui/Lib/libdepui.a Scene/libscene.a

# Rules
all: lib exe

contrib/grx248/lib/dj2/libgrx20.a:
	$(MAKE) -C contrib/grx248 -f makefile.dj2 libs

plush/libplush.a:
	$(MAKE) -C plush/src -f MAKEFILE	

Depui/Lib/libdepui.a:
	$(MAKE) -C Depui -f MAKEFILE lib

Scene/libscene.a:
	$(MAKE) -C Scene -f MAKEFILE

MatEdit2/matedit2.exe: $(LIB)
	$(MAKE) -C MatEdit2 -f MAKEFILE

PlushPlayer/plushplr.exe: $(LIB)
	$(MAKE) -C PlushPlayer -f MAKEFILE

clean:
	rm -f $(EXE)
	$(MAKE) -C plush/src -f MAKEFILE clean	
	$(MAKE) -C contrib/grx248 -f makefile.dj2 clean
	rm -f contrib/grx248/lib/dj2/libgrx20.a
	$(MAKE) -C Depui -f MAKEFILE clean
	$(MAKE) -C Scene -f MAKEFILE clean
	$(MAKE) -C MatEdit2 -f MAKEFILE clean
	$(MAKE) -C PlushPlayer -f MAKEFILE clean

# Dependencies

exe: $(EXE)

plushplr.exe: PlushPlayer/plushplr.exe 
	cp PlushPlayer/plushplr.exe .	

matedit2.exe: MatEdit2/matedit2.exe
	cp MatEdit2/matedit2.exe .

lib: $(LIB)
