EXELIBRARIES = depui grx20 scene expat plush

INCLUDE_DIRS += ../contrib/grx248/include ../depui/include ../plush/src ../Scene/src
LIBRARY_DIRS += ../contrib/grx248/lib/dj2 ../depui/lib ../plush ../Scene ../expat-1.95.2/libs

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = gxx
CPPFLAGS += -gstabs+ $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: matedit2

matedit: matedit2.exe

%exe : %o
	$(LINK.o) $^ $(LDLIBS) -o $@

clean:
	for %j in (*.o *.exe) do del %j

# Dependencies

matedit2.exe:  matedit2.o 

matedit2.o: matedit2.cpp matedit2.h
