test.exe: test.o grchart.a
	gcc -o test.exe test.o grchart.a -lgrx20 -mwindows
test.o: test.c grchart.h
	gcc -c test.c
grchart.a: grchart.o
	ar -r grchart.a grchart.o
grchart.o: grchart.c grchart.h
	gcc -c grchart.c
