LIBNAME = lib/libdepui.a
EXELIBRARIES = depui grx20X X11 stdc++
EXEEXTRA =

INCLUDE_DIRS += ../contrib/grx248/include
LIBRARY_DIRS += ../contrib/grx248/lib/unix


include mrules.inc
include mlinux.inc


