LIBNAME = lib/libdepui.a
EXELIBRARIES = depui grx20
EXEEXTRA = 

INCLUDE_DIRS += ../contrib/grx248/include
LIBRARY_DIRS += ../contrib/grx248/lib/dj2


include mrules.inc
include mdos.inc


