#
# Szene makefile for DJGPP version (GNU-make)
#
vpath_src = src
vpath %.cpp $(vpath_src)

EXELIBRARIES = scene depui grx20X plush expat X11 m stdc++

INCLUDE_DIRS += ../Scene/src ../contrib/grx248/include ../depui/include ../expat-1.95.2/source/lib ../plush/src
LIBRARY_DIRS += ../Scene ../contrib/grx248/lib/unix ../depui/lib ../expat-1.95.2/libs ../plush

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = g++
CPPFLAGS += -ggdb
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: plushplr.exe scenetst.exe 

plushplr.exe: PlushPlayer.o
	$(LINK.o) $^ $(LDLIBS) -o $@

%exe : %o
	$(LINK.o) $^ $(LDLIBS) -o $@

clean:
	for %j in ( *.exe *.a *.o) do del %j  


# Dependencies

scenetst.exe: scenetst.o ../Scene/libscene.a

plushplr.exe: PlushPlayer.o ../Scene/libscene.a
