#
# Szene makefile for DJGPP version (GNU-make)
#
vpath_src = src
vpath %.cpp $(vpath_src)

EXELIBRARIES = scene depui grx20X plush expat X11 m stdc++

INCLUDE_DIRS += ../Scene/src ../contrib/grx248/include ../depui/include ../expat-1.95.2/source/lib ../plush/src
LIBRARY_DIRS += ../Scene ../contrib/grx248/lib/unix ../depui/lib ../expat-1.95.2/libs ../plush

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = g++
ifdef DEBUG
CPPFLAGS += -ggdb
else
CPPFLAGS += -O3
endif
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: PlushPlayer

PlushPlayer: PlushPlayer.o $(PARENTLIBS)
	$(LINK.o) $< $(LDLIBS) -o $@

clean:
	rm -f PlushPlayer *.o

# Dependencies

include ../mrules.inc