#
# Szene makefile for DJGPP version (GNU-make)
#
vpath_src = src
vpath %.cpp $(vpath_src)

LIBOBJ=	sc_tokens.o Scene.o Controller.o SceneDesktop.o MoveMode.o \
	WalkMode.o FlyMode.o Hud.o Command.o HudRefreshCmd.o dbgprint.o Logger.o

INCLUDE_DIRS += src ../contrib/grx243/include ../depui/include ../expat-1.95.2/source/lib ../plush/src
LIBRARY_DIRS += ../contrib/grx243/lib/dj2 ../depui/lib ../expat-1.95.2/libs ../plush

INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = gxx
CPPFLAGS += -ggdb -DDEBUG
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: lib

lib: libscene.a $(LIBOBJ)

libscene.a: $(LIBOBJ)
	$(AR) rs $@ $^

clean:
	rm -f *.a *.o


# Dependencies


Scene.o: src/Scene.cpp src/Scene.h

Command.o: src/Command.cpp \
	src/Command.h

Controller.o: src/Controller.cpp \
	src/Controller.h \
	src/MoveMode.h src/Scene.h src/sc_tokens.h

Desktop.o: src/Desktop.cpp \
	src/Controller.h src/MoveMode.h \
	src/Scene.h src/sc_tokens.h src/WalkMode.h src/MoveMode.h src/FlyMode.h \
	src/MoveMode.h src/Hud.h src/HudRefreshCmd.h src/Command.h

FlyMode.o: src/FlyMode.cpp src/FlyMode.h \
	src/MoveMode.h src/Scene.h src/sc_tokens.h

Hud.o: src/Hud.cpp src/Hud.h

HudRefreshCmd.o: src/HudRefreshCmd.cpp src/HudRefreshCmd.h \
	src/Command.h src/Hud.h

MoveMode.o: src/MoveMode.cpp src/MoveMode.h

sc_tokens.o: src/sc_tokens.cpp src/sc_tokens.h

Scene.o: src/Scene.cpp src/Scene.h src/sc_tokens.h \
	src/Command.h

WalkMode.o: src/WalkMode.cpp src/WalkMode.h \
	src/MoveMode.h src/Scene.h src/sc_tokens.h
