#
# Szene makefile for DJGPP version (GNU-make)
#
vpath_src = src
vpath %.cpp $(vpath_src)

EXELIBRARIES = grx20 plush

INCLUDE_DIRS +=  ../contrib/grx243/include ../plush/src
LIBRARY_DIRS += ../contrib/grx243/lib/dj2 ../plush

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = gxx
CPPFLAGS += -gstabs+
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: exe

exe: dspl3ds.exe

dspl3ds.exe: DSPL3DS.o
	$(LINK.o) $^ $(LDLIBS) -o $@

clean:
	for %j in ( *.exe *.a *.o) do del %j  


# Dependencies

DSPL3DS.o: DSPL3DS.cc