test: test.o grchart.a
	gcc -o test test.o grchart.a libgrx20.a -lvga
test.o: test.c grchart.h
	gcc -c test.c
grchart.a: grchart.o
	ar -r grchart.a grchart.o
grchart.o: grchart.c grchart.h
	gcc -c grchart.c
