EXELIBRARIES = scene depui grx20X plush expat X11 m stdc++

INCLUDE_DIRS += ../contrib/grx248/include ../depui/include ../plush/src ../Scene/src
LIBRARY_DIRS += ../contrib/grx248/lib/unix ../depui/lib ../plush ../Scene ../expat-1.95.2/libs

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = g++
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

ifdef DEBUG
CPPFLAGS += -ggdb
else
CPPFLAGS += -O3
endif

all: Matedit

Matedit : matedit.o $(PARENTLIBS)
	$(LINK.o) $< $(LDLIBS) -o $@

clean:
	rm -f Matedit *.o

# Dependencies

matedit.o: matedit.cpp matedit.h

include ../mrules.inc