#
# Makefile for DJGPP version (GNU-make)
#

OBJECTS=xmlparse.o \
	xmlrole.o \
	xmltok.o

LIB = ..\..\libs\libexpat.a
CFLAGS += -I. -gstabs+ -xc -DVERSION=\"expat_1.95.2\" -fexceptions

all: $(LIB)

$(LIB): $(OBJECTS)
	$(AR) rs $@ $?

clean:
	for %i in ($(OBJECTS) $(LIB)) do del %i

install:

uninstall:


