#
# Szene makefile for DJGPP version (GNU-make)
#
vpath_src = src
vpath %.cpp $(vpath_src)

EXELIBRARIES = plush

OBJ=splinetest.o 

INCLUDE_DIRS += ../plush/src
LIBRARY_DIRS += ../plush

EXELIBS = $(addprefix -l,$(EXELIBRARIES))
INCLUDES = $(addprefix -I,$(INCLUDE_DIRS))
LIB_DIRS = $(addprefix -L,$(LIBRARY_DIRS))

CC = gxx
CPPFLAGS += -gstabs+
CPPFLAGS += $(INCLUDES)

LDLIBS = $(LIB_DIRS) $(EXELIBS)

all: splinetest.exe

splinetest.exe: $(OBJ)

%exe : %o
	$(LINK.o) $^ $(LDLIBS) -o $@

clean:
	for %j in ( *.exe *.o) do del %j  


# Dependencies

splinetest.o: splinetest.cpp
